#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraMode_HeldObject_TnTina

#include "Basic.hpp"

#include "Athena_PlayerCameraMode_HeldObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraMode_HeldObject_TnTina.Athena_PlayerCameraMode_HeldObject_TnTina_C
// 0x0000 (0x0DA0 - 0x0DA0)
class UAthena_PlayerCameraMode_HeldObject_TnTina_C final : public UAthena_PlayerCameraMode_HeldObject_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_PlayerCameraMode_HeldObject_TnTina_C">();
	}
	static class UAthena_PlayerCameraMode_HeldObject_TnTina_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraMode_HeldObject_TnTina_C>();
	}
};

}

