#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_CCPM_Base_Niagara_Professor_Pup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_CCPM_Base_Niagara_Template_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_CCPM_Base_Niagara_Professor_Pup.B_CCPM_Base_Niagara_Professor_Pup_C
// 0x0018 (0x03F8 - 0x03E0)
class AB_CCPM_Base_Niagara_Professor_Pup_C final : public AB_CCPM_Base_Niagara_Template_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_CCPM_Base_Niagara_Professor_Pup_C; // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AFortPlayerPawnAthena*                  Fort_Pawn_Player;                                  // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DoOnce;                                            // 0x03F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_B_CCPM_Base_Niagara_Professor_Pup(int32 EntryPoint);
	void OnPawnAndPartChanged();
	void ResetSprint();
	void Character_Movement_Updated(float DeltaSeconds, const struct FVector& OldLocation, const struct FVector& OldVelocity);
	void OnBeginSkydiving();
	void OnEndSkydiving();
	void Enter_Vehicle();
	void Exit_Vehicle();
	void OnHitPawn(class AActor* SelfActor, class AActor* OtherActor, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void ResIn();
	void ResOut();
	void Night_Phase(bool At_Creation);
	void Evening_Phase(bool At_Creation);
	void Day_Phase(bool At_Creation);
	void Morning_Phase(bool At_Creation);
	void OnTargetingOrFirstPersonCameraChanged();
	void GetIsDriving(bool* Param_IsDriving);
	void Set_Niagara_System_User_Variable__Color_(class FName Param_Name, const struct FLinearColor& Value);
	void Set_Niagara_System_User_Variable__Float_(class FName Param_Name, float Value);
	void Set_Niagara_System_User_Variable__Int_(class FName Param_Name, int32 Value);
	void Set_Niagara_System_User_Variable__Vector_(class FName Param_Name, const struct FVector& Value);
	void Set_Niagara_System_User_Variable__Bool_(class FName Param_Name, bool Value);
	void GetNiagaraParticles(struct FGameplayTagContainer* Gameplay_Tag_Container);
	void GetIsFrontEnd(bool* Param_IsInFrontEnd);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_CCPM_Base_Niagara_Professor_Pup_C">();
	}
	static class AB_CCPM_Base_Niagara_Professor_Pup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_CCPM_Base_Niagara_Professor_Pup_C>();
	}
};

}

