#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusTabMinusMain_Bacchus

#include "Basic.hpp"

#include "ButtonStyleMinusTabMinusMain_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Tab-Main_Bacchus.ButtonStyle-Tab-Main_Bacchus_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyleMinusTabMinusMain_Bacchus_C final : public UButtonStyleMinusTabMinusMain_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Tab-Main_Bacchus_C">();
	}
	static class UButtonStyleMinusTabMinusMain_Bacchus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusTabMinusMain_Bacchus_C>();
	}
};

}

