#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusLightbox

#include "Basic.hpp"

#include "ButtonStyleMinusBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Lightbox.ButtonStyle-Lightbox_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyleMinusLightbox_C final : public UButtonStyleMinusBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Lightbox_C">();
	}
	static class UButtonStyleMinusLightbox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusLightbox_C>();
	}
};

}

