#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusTabMinusMainMinusRecolorMinusRed

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Tab-Main-Recolor-Red.ButtonStyle-Tab-Main-Recolor-Red_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyleMinusTabMinusMainMinusRecolorMinusRed_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Tab-Main-Recolor-Red_C">();
	}
	static class UButtonStyleMinusTabMinusMainMinusRecolorMinusRed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusTabMinusMainMinusRecolorMinusRed_C>();
	}
};

}

