#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusTransparentPlayerSurveyMinusXSMinusB1

#include "Basic.hpp"

#include "ButtonStyleMinusMediumTransparentNoCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-TransparentPlayerSurvey-XS-B1.ButtonStyle-TransparentPlayerSurvey-XS-B1_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyleMinusTransparentPlayerSurveyMinusXSMinusB1_C final : public UButtonStyleMinusMediumTransparentNoCues_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-TransparentPlayerSurvey-XS-B1_C">();
	}
	static class UButtonStyleMinusTransparentPlayerSurveyMinusXSMinusB1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusTransparentPlayerSurveyMinusXSMinusB1_C>();
	}
};

}

