#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Creative_Device_Effects_Interface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Creative_Device_Effects_Interface.Creative_Device_Effects_Interface_C
// 0x0000 (0x0028 - 0x0028)
class ICreative_Device_Effects_Interface_C final : public IInterface
{
public:
	void Get_Creative_Effect_Data(struct FFCreativeEffectColorIndex* Effect_Color);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Creative_Device_Effects_Interface_C">();
	}
	static class ICreative_Device_Effects_Interface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ICreative_Device_Effects_Interface_C>();
	}
};

}

