#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginInteractionHost

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LoginInteractionHost.LoginInteractionHost_C
// 0x0008 (0x0560 - 0x0558)
class ULoginInteractionHost_C final : public UFortLoginInteractions
{
public:
	class USafeZone*                              SafeZone_0;                                        // 0x0558(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LoginInteractionHost_C">();
	}
	static class ULoginInteractionHost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoginInteractionHost_C>();
	}
};

}

