#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusButtonMinusPrimaryMinusLSkew

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Button-Primary-LSkew.TextStyle-Button-Primary-LSkew_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyleMinusButtonMinusPrimaryMinusLSkew_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Button-Primary-LSkew_C">();
	}
	static class UTextStyleMinusButtonMinusPrimaryMinusLSkew_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusButtonMinusPrimaryMinusLSkew_C>();
	}
};

}

