#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_BurbankSmall_S_DarkGrey

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle_BurbankSmall_S_DarkGrey.TextStyle_BurbankSmall_S_DarkGrey_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyle_BurbankSmall_S_DarkGrey_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle_BurbankSmall_S_DarkGrey_C">();
	}
	static class UTextStyle_BurbankSmall_S_DarkGrey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_BurbankSmall_S_DarkGrey_C>();
	}
};

}

